development:
  adapter: postgresql
  encoding: unicode
  database: kupon_development
  username: developer
  host: localhost
  pool: 5

test:
  adapter: postgresql
  encoding: unicode
  database: kupon_test
  username: developer
  host: localhost
  pool: 5

